-- Seed Data for places
-- Member 3: Demo places data (IDs 101-108)

INSERT INTO places (
    id, name, description, locality, latitude, longitude, category,
    hidden_score, popularity_score, curation_score, best_visit_time,
    image_url, source_name, source_ref, wheelchair_accessible,
    parking_available, public_transport, walking_difficulty, active, created_at
) VALUES
(
    101,
    'Chand Baori',
    'One of the largest and most beautiful stepwells in India. Built in the 9th century, it has 3,500 narrow steps over 13 storeys.',
    'Abhaneri, Rajasthan',
    27.007300,
    76.606500,
    'heritage',
    30,
    85,
    90,
    'October to March',
    'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1',
    'Rajasthan Tourism',
    'https://www.tourism.rajasthan.gov.in/',
    FALSE,
    TRUE,
    FALSE,
    'MODERATE',
    TRUE,
    NOW()
),
(
    102,
    'Auniati Satra',
    'A prominent 17th-century Vaishnavite monastery in Majuli, Assam. Established in 1653, it is a key center of Neo-Vaishnavite culture and Sattriya arts.',
    'Majuli, Assam',
    26.953500,
    94.156500,
    'spiritual',
    60,
    50,
    75,
    'November to March',
    'https://images.unsplash.com/photo-1545205597-3d9d02c29597',
    'Assam Tourism',
    'https://assamtourism.gov.in/',
    TRUE,
    TRUE,
    TRUE,
    'EASY',
    TRUE,
    NOW()
),
(
    103,
    'Pochampally Ikat Weaving Cluster',
    'A world-famous weaving village known for its unique geometric double-ikat patterns. Often called the Silk City of India, it received GI status in 2005.',
    'Bhoodan Pochampally, Telangana',
    17.345600,
    78.825200,
    'cultural',
    55,
    60,
    80,
    'September to February',
    'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb',
    'Telangana Tourism',
    'https://www.telanganatourism.gov.in/',
    TRUE,
    TRUE,
    TRUE,
    'EASY',
    TRUE,
    NOW()
),
(
    104,
    'Bhadrawati Palace',
    'An ancient 11th-century palace located in Bhandarej, blending Rajput and Mughal architectures. It has been restored into a heritage hotel.',
    'Bhandarej, Rajasthan',
    26.901500,
    76.381200,
    'heritage',
    70,
    40,
    70,
    'October to March',
    'https://images.unsplash.com/photo-1598977123418-45f04b61b49e',
    'Rajasthan Tourism',
    'https://www.tourism.rajasthan.gov.in/',
    TRUE,
    TRUE,
    FALSE,
    'EASY',
    TRUE,
    NOW()
),
(
    105,
    'Majuli River Island',
    'The world''s largest inhabited river island, situated on the Brahmaputra River. It is a hub of Assamese Vaishnavite culture, satras, and pristine nature.',
    'Majuli, Assam',
    26.960200,
    94.195000,
    'nature',
    40,
    70,
    85,
    'October to March',
    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
    'Assam Tourism',
    'https://assamtourism.gov.in/',
    FALSE,
    TRUE,
    FALSE,
    'EASY',
    TRUE,
    NOW()
),
(
    106,
    'Muzhappilangad Drive-in Beach',
    'The longest drive-in beach in Asia and the only one in Kerala. Visitors can drive their vehicles directly along the 4 km stretch of firm sands.',
    'Kannur, Kerala',
    11.791500,
    75.438500,
    'beach',
    35,
    75,
    80,
    'September to May',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
    'Kerala Tourism',
    'https://www.keralatourism.org/',
    TRUE,
    TRUE,
    TRUE,
    'EASY',
    TRUE,
    NOW()
),
(
    107,
    'Dzukou Valley',
    'A breathtakingly beautiful valley located on the border of Nagaland and Manipur, famous for its seasonal flowers, green hills, and trekking paths.',
    'Kohima, Nagaland',
    25.602500,
    94.067300,
    'nature',
    65,
    60,
    90,
    'June to September',
    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b',
    'Nagaland Tourism',
    'https://tourism.nagaland.gov.in/',
    FALSE,
    FALSE,
    FALSE,
    'HARD',
    TRUE,
    NOW()
),
(
    108,
    'Gandikota Gorge',
    'Known as the Grand Canyon of India, Gandikota is a stunning gorge formed by the Penna River cut through the Erramala hills, featuring a historic fort.',
    'Kadapa, Andhra Pradesh',
    14.814200,
    78.286600,
    'nature',
    45,
    70,
    85,
    'September to February',
    'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800',
    'Andhra Pradesh Tourism',
    'https://tourism.ap.gov.in/',
    FALSE,
    TRUE,
    FALSE,
    'MODERATE',
    TRUE,
    NOW()
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    locality = EXCLUDED.locality,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    category = EXCLUDED.category,
    hidden_score = EXCLUDED.hidden_score,
    popularity_score = EXCLUDED.popularity_score,
    curation_score = EXCLUDED.curation_score,
    best_visit_time = EXCLUDED.best_visit_time,
    image_url = EXCLUDED.image_url,
    source_name = EXCLUDED.source_name,
    source_ref = EXCLUDED.source_ref,
    wheelchair_accessible = EXCLUDED.wheelchair_accessible,
    parking_available = EXCLUDED.parking_available,
    public_transport = EXCLUDED.public_transport,
    walking_difficulty = EXCLUDED.walking_difficulty,
    active = EXCLUDED.active,
    created_at = EXCLUDED.created_at;

-- Adjust sequence to avoid collision in future inserts
SELECT setval(
    pg_get_serial_sequence('places', 'id'),
    (SELECT MAX(id) FROM places)
);
